AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sncf-max-confirmator

  Sample SAM Template for sncf-max-confirmator
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Resources:
  ConfirmTravelsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/confirm-travels/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ConfirmTravels:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /confirm-travels
            Method: get
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: ssm:GetParameter
              Resource: arn:aws:ssm:eu-west-3:992848035821:parameter/SNCFMaxJeune/refreshToken
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ConfirmTravelsApi:
    Description: "API Gateway endpoint URL for Prod stage for Confirm Travels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/confirm-travels/"
  ConfirmTravelsFunction:
    Description: "Confirm Travels Lambda Function ARN"
    Value: !GetAtt ConfirmTravelsFunction.Arn
  ConfirmTravelsFunctionIamRole:
    Description: "Implicit IAM Role created for Confirm Travels function"
    Value: !GetAtt ConfirmTravelsFunctionRole.Arn
